CREATE TABLE IF NOT EXISTS country_queries (
  country TEXT PRIMARY KEY,
  query_count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS query_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  country TEXT NOT NULL,
  plate_code TEXT,
  queried_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
